name: Bryce Mueller | Software Engineer
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "www.brycemueller.com"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME